tech:
  data_dir: "../data"

data:
  file: canada_dataset.xls
  start_year: 1980
  end_year: 2000

model:
  coeffs:
    a: "0.001;1"
    gamma: "0.001;1"
    alpha_k: "0.001;1"
    n: "0.001;5"
    s: "0.001;1"
    delta: "0.001;1"
  n_splits: 5
  n_threads: 4